### ISSUE TITLE
ServerlessFunction Resource: `CodeUri` Property Required Despite Setting `InlineCode` Property

### ISSUE THREAD

**Issue by joel-aws** [aws/aws-toolkit-vscode#1107]
**Describe the bug**

With a resource of type `AWS::Serverless::Function`, when using the `InlineCode` property and not setting `CodeUri`, upon deploying, the following error occurs:

```sh
Missing or invalid value in Template for key: CodeUri
An error occurred while deploying a SAM Application. Check the logs for more information by running the "View AWS Toolkit Logs" command from the Command Palette.
```

**To Reproduce**

1. In `template.yml`, create a resource like:

```yml
rStringSplitterFunction:
  Type: AWS::Serverless::Function
  Properties:
    InlineCode: |
      import json
      import cfnresponse
      def lambda_handler(event, context):
          responseData = {"Data": "hello world"}
          cfnresponse.send(event, context, cfnresponse.SUCCESS, responseData)
    Handler: index.lambda_handler
    Runtime: python3.6
```

2. From the Toolkit select `Deploy SAM Application`

**Expected behavior**

Expected the application to deploy, like when I use `sam build && sam deploy --guided` from the terminal.

**Desktop (please complete the following information):**

-   OS: Darwin x64 18.7.0
-   Visual Studio Code Version: 1.45.1
-   AWS Toolkit Version: 1.9.0

**Comment by fkreis** [comment]
Just stumbled across the same problem when using cdk's [CfnInclude](https://docs.aws.amazon.com/cdk/api/latest/docs/cloudformation-include-readme.html) with a template that contains a Function with InlineCode.

Since I needed to find out my self how to workaround this problem I wanted to leave a note here. It is possible to put a **dummy value into 'CodeUri'** and still the code from InlineCode will be picked up.

Example:
```yaml
MyLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: python3.7
      Timeout: 300
      CodeUri: mandatory but ignored value due to https://github.com/aws/aws-toolkit-vscode/issues/1107
      InlineCode: |
        import json
        [...]
```
