### ISSUE TITLE
Failed to deploy SAM application with reason of Template error: instance of Fn::GetAtt references undefined resource HelloWorldFunctionRole

### ISSUE THREAD

**Issue by kenchoong** [aws/aws-toolkit-vscode#1302]
**Desktop (please complete the following information):**

-   OS: Window 10
-   VS Code version:  1.49.0(User setup) 
-   AWS Toolkit extension version: AWS 1.13.0

**Question**

I want to deploy my `HelloWorldFunction`  template(Generate by Hello World basic app) , I done the following: 

1) Ctrl + Shift + P
2) AWS: Deploy SAM aplication
3) choose template.yaml
4) Select region
5) Enter name for S3 bucket created 
6) Enter name of stack 

Then I get this error when deploy: 

```
Error: Error with child process: Error: Failed to create changeset for the stack: my-stack, ex: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. 
Reason: Template error: instance of Fn::GetAtt references undefined resource HelloWorldFunctionRole
Deploy failed
```

It said undefined resource for HelloWorldFunctionRole. But I already stated the Role Arn in my HelloWorldFunction. 

Here is my template.yaml: 

```
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  MyLambda

  Sample SAM Template for MyLambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.8
      Role: HERE I set the role arn that I created in AWS console  ** Here is what I add 
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn


```

All the above code is generated by **AWS SAM Hello World** template, I just add the **Role Arn** value in the field under Runtime as u see above.. 

What I have done: 

1) Created a role in AWS IAM Management Console.
2) Attach policy as **LambdaBasicExecutionPolicy** for the role
3) Copy **Role Arn** value to template.yaml as shown above 

Then when deploy, I get the error as mention above. 

Please give some guidance, don't know what I missing out so far.

**Comment by bryceitoc9** [comment]
Hi @kenchoong 

Could you try deleting the `HelloWorldFunctionIamRole` from the `Output` section? SAM [autogenerates a role](https://github.com/aws/serverless-application-model/blob/master/docs/internals/generated_resources.rst#awsserverlessfunction), I believe using those parameters. Removing this should let you manually set a role.

**Comment by kenchoong** [comment]
hey @bryceitoc9 ,thanks for the guidance. 

It works now after delete `HelloWorldFunctionIamRole` from `Output`. 

Thank you very much

**Comment by aaaaayushh** [comment]
Hey I'm facing the same issue, but after deleting the IAMRole from output, I'm getting the following error during sam deploy:
![Screenshot from 2022-01-29 15-37-49](https://user-images.githubusercontent.com/55553065/151656869-663ba968-2a32-4d20-b89d-77d4db394e8a.png)

My template.yaml is:
```
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  get-better

  Sample SAM Template for get-better

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  GetBetterFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: code
      Handler: app.lambda_handler
      Runtime: python3.7
      MemorySize: 1024
      Role: #here I inserted the role I created
      Environment:
        Variables:
          s3_bucket: get-better
          model_name: model.pkl
      Architectures:
        - x86_64
      Events:
        GetBetter:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /classify
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GetBetterApi:
    Description: "API Gateway endpoint URL for Prod stage for Get Better function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/get-better/" #hello
  GetBetterFunction:
    Description: "Get Better Lambda Function ARN"
    Value: !GetAtt GetBetterFunction.Arn
  GetBetterFunctionIamRole:
    Description: "Implicit IAM Role created for Get Better function"
    Value: !GetAtt GetBetterRole.Arn
```
Any help would be highly appreciated!
