### ISSUE TITLE
samconfig.toml env_vars are overridden by launch.json

### ISSUE THREAD

**Issue by danw-mpl** [aws/aws-toolkit-vscode#1946]
**Describe the bug**

When the extension is used to launch a SAM Lambda function using a launch.json configuration, environment variables for the Lambda function are overridden even if `env_vars` is configured in `samconfig.toml`.

**Workarounds**

- Run the SAM commands manually, bypassing the toolkit.  Environment variables configured in `samconfig.toml` are passed to Lambda as expected.  This workaround gives up the ability to debug since we're not using the toolkit.

  ```shell
  sam build --template Template.yaml --use-container
  # --config-file is required when samconfig.toml is not within the same directory as template.yaml
  sam local invoke MyFunction -t .aws-sam/build/template.yaml --config-file ../../samconfig.toml
  ```

- Configure `environmentVariables` within `launch.json` instead of `samconfig.toml`.  This is per-function and also VS Code-specific.

**To Reproduce**

1. Create `.vscode/launch.json`:

  ```json
  {
      "configurations": [
          {
              "type": "aws-sam",
              "request": "direct-invoke",
              "name": "project:MyFunction",
              "invokeTarget": {
                  "target": "template",
                  "templatePath": "${workspaceFolder}/Template.yaml",
                  "logicalId": "MyFunction"
              },
              "lambda": {
                  "payload": {},
              },
              "sam": {
                  "localArguments": ["--config-file", "${workspaceFolder}/samconfig.toml"],
              }
          }
      ]
  }
  ```

2. Create `samconfig.toml`

  ```toml
  version = 0.1
  
  [default.build.parameters]
  # use_container required to avoid spurious errors such as
  # Error: PythonPipBuilder:ResolveDependencies - list index out of range
  use_container = "true"
  
  [default.local_invoke.parameters]
  # env_vars required to pass environment variables to the
  # Lambda function image container when debugging locally.
  env_vars = "env-vars.json"
  ```

3. Create `env-vars.json`

```json
{
    "Parameters": {
        "S3_ENDPOINT_URL": "http://localstack:4566",
        "SNS_ENDPOINT_URL": "http://localstack:4566",
        "DYNAMODB_ENDPOINT": "http://localstack:4566"
    }
}
```

**Behaviour using Toolkit**

```shell
$:~/repositories/project$ cat /tmp/aws-toolkit-vscode/vsctkG3cdmX/env-vars.json 
{"MyFunction":{}}
```

```python
print(os.environ.get('S3_ENDPOINT_URL'))
''
```

**Behaviour using SAM CLI directly**

```python
print(os.environ.get('S3_ENDPOINT_URL'))
'http://localstack:4566'
```

**Expected behavior**

The Toolkit should not override environment variables set by `samconfig.toml`.

**Desktop**

-   OS: Linux x64 5.4.72-microsoft-standard-WSL2
-   Visual Studio Code Version: 1.59.0
-   AWS Toolkit Version: 1.28.0
