### ISSUE TITLE
sam.schema.json: invalid policy document

### ISSUE THREAD

**Issue by LucasZielke** [aws/aws-toolkit-vscode#1974]
**Describe the bug**

VS Code throws up errors for adding a list of policies in a Serverless::Functions Properties stating that: 
`Incorrect type. Expected "string".yaml-schema: file://.../globalStorage/amazonwebservices.aws-toolkit-vscode/sam.schema.json`

**To Reproduce**
```
lambdaHandler:
  Type: AWS::Serverless::Function
  Properties:
    Policies:
      - Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource: !Ref Secret
          - Effect: Allow
            Action:
              - states:StartExecution
            Resource: !Ref stepFunction
```

**Expected behavior**

It shouldnt be throwing up errors as its being accepted by sam deploy fine

**Desktop (please complete the following information):**

-   OS: Darwin x64 20.6.0
-   Visual Studio Code Version: 1.59.1
-   AWS Toolkit Version: 1.29.0
