### ISSUE TITLE
sam.schema.json: add "architecture" field for SAM

### ISSUE THREAD

**Issue by justinmk3** [aws/aws-toolkit-vscode#2126]
SAM introduced the "architecture" field to support the similar new field on Lambda, in particular for ARM.

This field needs to be added/upstreamed to https://github.com/awslabs/goformation SAM schema.

**Comment by jpinkney-aws** [comment]
@justinmk3 Is this for `AWS::Serverless::Function`?

If so, it looks like someone has added it to the schema as:
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  MyApi:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
        - arm64
```

validates correctly
