### ISSUE TITLE
AWS SAM: Property SSMParameterReadPolicy is not allowed

### ISSUE THREAD

**Issue by pmateosc** [aws/aws-toolkit-vscode#2250]
**Describe the bug**
I'm using sam templates for creating a function and vscode finds an error when I add the policy template: "SSMParameterReadPolicy" as follows:
```yaml
  UpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.9
      FunctionName: !Sub enterprise-update-${Stage}
      CodeUri: "../../src/clients-update"
      Description: function for updating (activate or deactivate) clients
      PackageType: Zip
      MemorySize: 128
      Timeout: 10
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /clients/endclients/{endClientId}
            Method: PATCH
            RestApiId: !Ref EnterpriseApi
      Environment:
        Variables:
          STAGE: !Ref Stage
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoClients
        - SSMParameterReadPolicy: # <-- Problem: Property SSMParameterReadPolicy is not allowed
            ParameterName: "application/*"
```
The problem message is: **Property SSMParameterReadPolicy is not allowed** in the first line of the policy. 

If I search this policy template in the sam.schema.json I can't see it, so I think this could be the principal cause of the error. This is what I have in the sam.schema.json:
```json
"AWS::Serverless::Function.SAMPolicyTemplate": {
            "additionalProperties": false,
            "properties": {
                "AMIDescribePolicy": {
                    "$ref": "#/definitions/AWS::Serverless::Function.EmptySAMPT"
                },
                "CloudFormationDescribeStacksPolicy": {
                    "$ref": "#/definitions/AWS::Serverless::Function.EmptySAMPT"
                },
                "CloudWatchPutMetricPolicy": {
                    "$ref": "#/definitions/AWS::Serverless::Function.EmptySAMPT"
                },
                "DynamoDBCrudPolicy": {
                    "$ref": "#/definitions/AWS::Serverless::Function.TableSAMPT"
                },
                "DynamoDBReadPolicy": {
                    "$ref": "#/definitions/AWS::Serverless::Function.TableSAMPT"
                },
                "DynamoDBStreamReadPolicy": {
                    "$ref": "#/definitions/AWS::Serverless::Function.TableStreamSAMPT"
                },
                "EC2DescribePolicy": {
                    "$ref": "#/definitions/AWS::Serverless::Function.EmptySAMPT"
                },
                "ElasticsearchHttpPostPolicy": {
                    "$ref": "#/definitions/AWS::Serverless::Function.DomainSAMPT"
                },
                "FilterLogEventsPolicy": {
                    "$ref": "#/definitions/AWS::Serverless::Function.LogGroupSAMPT"
                },
                "KMSDecryptPolicy": {
                    "$ref": "#/definitions/AWS::Serverless::Function.KeySAMPT"
                },
                "KinesisCrudPolicy": {
                    "$ref": "#/definitions/AWS::Serverless::Function.StreamSAMPT"
                },
                "KinesisStreamReadPolicy": {
                    "$ref": "#/definitions/AWS::Serverless::Function.StreamSAMPT"
                },
                "LambdaInvokePolicy": {
                    "$ref": "#/definitions/AWS::Serverless::Function.FunctionSAMPT"
                },
                "RekognitionDetectOnlyPolicy": {
                    "$ref": "#/definitions/AWS::Serverless::Function.EmptySAMPT"
                },
                "RekognitionLabelsPolicy": {
                    "$ref": "#/definitions/AWS::Serverless::Function.EmptySAMPT"
                },
                "RekognitionNoDataAccessPolicy": {
                    "$ref": "#/definitions/AWS::Serverless::Function.CollectionSAMPT"
                },
                "RekognitionReadPolicy": {
                    "$ref": "#/definitions/AWS::Serverless::Function.CollectionSAMPT"
                },
                "RekognitionWriteOnlyAccessPolicy": {
                    "$ref": "#/definitions/AWS::Serverless::Function.CollectionSAMPT"
                },
                "S3CrudPolicy": {
                    "$ref": "#/definitions/AWS::Serverless::Function.BucketSAMPT"
                },
                "S3ReadPolicy": {
                    "$ref": "#/definitions/AWS::Serverless::Function.BucketSAMPT"
                },
                "SESBulkTemplatedCrudPolicy": {
                    "$ref": "#/definitions/AWS::Serverless::Function.IdentitySAMPT"
                },
                "SESCrudPolicy": {
                    "$ref": "#/definitions/AWS::Serverless::Function.IdentitySAMPT"
                },
                "SESEmailTemplateCrudPolicy": {
                    "$ref": "#/definitions/AWS::Serverless::Function.EmptySAMPT"
                },
                "SESSendBouncePolicy": {
                    "$ref": "#/definitions/AWS::Serverless::Function.IdentitySAMPT"
                },
                "SNSCrudPolicy": {
                    "$ref": "#/definitions/AWS::Serverless::Function.TopicSAMPT"
                },
                "SNSPublishMessagePolicy": {
                    "$ref": "#/definitions/AWS::Serverless::Function.TopicSAMPT"
                },
                "SQSPollerPolicy": {
                    "$ref": "#/definitions/AWS::Serverless::Function.QueueSAMPT"
                },
                "SQSSendMessagePolicy": {
                    "$ref": "#/definitions/AWS::Serverless::Function.QueueSAMPT"
                },
                "StepFunctionsExecutionPolicy": {
                    "$ref": "#/definitions/AWS::Serverless::Function.StateMachineSAMPT"
                },
                "VPCAccessPolicy": {
                    "$ref": "#/definitions/AWS::Serverless::Function.EmptySAMPT"
                }
            },
            "type": "object"
        },
```

Another point is that if I deploy the template, cloudformation does not return any type of error.

**To Reproduce**

Create a function with sam template and add the de policies parameter the following template:
```yaml
- SSMParameterReadPolicy: 
            ParameterName: "applications/*"
```

**Expected behavior**

at the moment you add this policy, that line will sows you the problem: Property SSMParameterReadPolicy is not allowed 

**Screenshots**

![imagen](https://user-images.githubusercontent.com/79842764/139451676-4ac01e96-7344-4416-916f-e1261818ac42.png)

**Desktop (please complete the following information):**

-   OS: Windows_NT x64 10.0.19043
-   Visual Studio Code Version: 1.61.2
-   AWS Toolkit Version: 1.32.0
