### ISSUE TITLE
"Deploy SAM Application": Cannot build layer dependencies: "[Errno 30] Read-only file system"

### ISSUE THREAD

**Issue by miyuk** [aws/aws-toolkit-vscode#2395]
**Describe the bug**

When use VS Command `Deploy SAM Application` with dependencies layer,
build status is `failed`.

However,　deploy process was continuing and create insufficient layer object(only requirements.txt file)

execution log is in `additional context`.

failed reason is `[Errno 30] Read-only file system: '.aws-sam'`.

when run command without AWS-ToolKit as below, dependencies ware resolved and create layer.

```bash
mkdir -p /tmp/aws-toolkit-vscode/samDeploytpFy2M/build 
 /usr/local/bin/sam build --build-dir /tmp/aws-toolkit-vscode/samDeploytpFy2M/build --template /Users/<USERNAME>/git/sam_test/lambda-python3.9/template.yaml
```

`template.yml`

```yaml
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Layers:
        - !Ref MyLayer
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
  MyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: Layer description
      ContentUri: my_layer/
      CompatibleRuntimes:
        - python3.9
    Metadata:
      BuildMethod: python3.9
```

`my_layer/requirements.txt` has only line: `requests`

**To Reproduce**

1. create python SAM Application template with layer
2. Add `requirements.txt` in layer directory
3. run VS Command `Deploy SAM Application`

**Expected behavior**
Build requirements.txt dependencies and create layer

**Desktop (please complete the following information):**

-   OS: Darwin x64 20.6.0
-   Visual Studio Code Extension Host Version: 1.63.2
-   AWS Toolkit Version: 1.34.

**Additional context**

[sam_deploy.log](https://github.com/aws/aws-toolkit-vscode/files/7798560/sam_deploy.log)

**Comment by JadenSimon** [comment]
Hey @miyuk,

Thanks for reporting this issue (and including a minimal example!). This looks like a problem with how SAM CLI caches layers. Do you have caching enabled? I only ask because I was unable to reproduce the issue until I turned on caching.

One workaround you can try is forcing the cache directory to be located in `tmp` by adding a `samconfig.toml` file to the root of the project:
```toml
version=0.1
[default.build.parameters]
cache_dir="/tmp/.aws-sam/cache"
```

The root-cause here is still unclear. Considering the command works when ran in a shell but fails when ran by the toolkit makes me think it's either a permissions issue or something with environment variables. If you could provides logs with your log level set to `debug` that would be very helpful! You can set the log level for the toolkit by going into VS Code's settings and searching for `Aws: Log-Level`.
