### ISSUE TITLE
Schema validation for StepFunctions inline IAM policies

### ISSUE THREAD

**Issue by benjymoses** [aws/aws-toolkit-vscode#2440]
**Describe the bug**

In the **Policies** property of an `AWS::Serverless::StateMachine`, inline policy definitions that follow on from AWS SAM Policy Templates are red highlighted with the following error:

> Property Version is not allowed.
> 
> yaml-schema: aws:{redactedUserHomeDirPath}/amazonwebservices.aws-toolkit-vscode/sam.schema.json

The corresponding template.yaml is valid and `sam deploy` is successful.

**To Reproduce**

1. Define an `AWS::Serverless::StateMachine` and a `AWS::Serverless::Function`
2. Under the **Policies** definition of the StateMachine specify a SAM Policy Template such as `LambdaInvokePolicy`
3. Follow this with an inline policy statement for example:

```yaml
Policies: 
        - LambdaInvokePolicy:
            FunctionName: !Ref MyLambdaFunction
        - Version: "2012-10-17"
          Statement: 
            - Effect: Allow
              Action:
                - "logs:CreateLogStream"
                - "logs:PutLogEvents"
                - "logs:CreateLogDelivery"
                - "logs:GetLogDelivery"
                - "logs:UpdateLogDelivery"
                - "logs:DeleteLogDelivery"
                - "logs:ListLogDeliveries"
                - "logs:PutResourcePolicy"
                - "logs:DescribeResourcePolicies"
                - "logs:DescribeLogGroups"
              Resource:
                - "*"
```

**Expected behavior**

I would expect syntax highlighting / linting to accept this and not highlight as an error.

**Desktop (please complete the following information):**

-   OS: macOS Monterey Version 12.1
-   Visual Studio Code Version: Version 1.63.2
-   AWS Toolkit Version: Version 1.35.0
