### ISSUE TITLE
Is it possible to use {proxy+} in my route for template-based API Gateway debugging?

### ISSUE THREAD

**Issue by ryancabanas** [aws/aws-toolkit-vscode#2446]
**Desktop (please complete the following information):**

-   OS: Windows 10
-   VS Code version: 1.63.2
-   AWS Toolkit extension version: 1.35.0

**Question**

I have an SAM template setup such that my API Gateway has a single route that consists only of `/{proxy+}` and with it I'm using Express JS.  In the [documentation](https://docs.aws.amazon.com/toolkit-for-vscode/latest/userguide/debug-apigateway.html), it states that the `api.path` value...

> Must be a valid API path resolved from the `template.yaml` specified by `invokeTarget.templatePath`.

I tried setting up `api.path` in the `launch.json` configuration with both a valid route and with `/{proxy+}` (which I knew wouldn't work, but hey), but I get the follow error in either case:

> [ERROR]: Local API failed to respond (ECONNREFUSED) after 30 retries, path: /{proxy+}, error: connect ECONNREFUSED 127.0.0.1:5860

Is it possible to use AWS Toolkit debugging with this setup?

Thanks.

**Comment by JadenSimon** [comment]
Hey @ryancabanas ,

Using `/{proxy+}` in a HelloWorldFunction template appears to work correctly for me. In my template I have
```yaml
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /foo/{proxy+}
            Method: get
```
And my `launch.json`:
```json
{
  "type": "aws-sam",
  "request": "direct-invoke",
  "name": "API lambda-nodejs14.x:HelloWorldFunction (nodejs14.x)",
  "invokeTarget": {
      "target": "api",
      "templatePath": "${workspaceFolder}/lambda-nodejs14.x/template.yaml",
      "logicalId": "HelloWorldFunction"
  },
  "api": {
      "path": "/foo/bar",
      "httpMethod": "get",
  },
  "lambda": {
      "runtime": "nodejs14.x"
  }
}
```

Succeeds with:
```
Debugger attached.
END RequestId: bc52d932-fb28-4578-8c6f-893832d18890
REPORT RequestId: bc52d932-fb28-4578-8c6f-893832d18890	Init Duration: 0.65 ms	Duration: 2601.88 ms	Billed Duration: 2602 ms	Memory Size: 128 MB	Max Memory Used: 128 MB	
2022-01-21 12:54:35,402 | Cleaning all decompressed code dirs
2022-01-21 12:54:35,403 | No Content-Type given. Defaulting to 'application/json'.
2022-01-21 12:54:35 127.0.0.1 - - [21/Jan/2022 12:54:35] "GET /foo/bar HTTP/1.1" 200 -
```

The specific error you mention is pretty much a generic failure for the local server either not starting or being too slow to respond. So there's many potential reasons for why this isn't working for your case. I'd need some additional details or your log output (use the `AWS: View Toolkit Logs` command). May also want to set your logging level to 'debug' via the VS Code setting `aws.logLevel`
