### ISSUE TITLE
ASL Pass state schema validation reports Parameters array as invalid

### ISSUE THREAD

**Issue by kjones** [aws/aws-toolkit-vscode#2459]
Getting `Incorrect type. Expected "object".` for the Parameters in the following:
```yaml
MyPassState:
  Type: Pass
  Next: MyMapState
  Parameters:
     - Prop1: Value1
       Prop2: Value2
     - Prop1: Value3
       Prop2: Value4
```
**Expected behavior**
No error should be produced. Parameters can be an array.

**Screenshots**
![image](https://user-images.githubusercontent.com/1952793/152260169-4a6a12a0-10ab-4be2-95d3-0d90e28c2f2d.png)

-   OS: MacOS 12.1
-   Visual Studio Code Version: 1.63.2
-   AWS Toolkit Version: 1.35.0
