### ISSUE TITLE
Support for comments in YAML State Machines

### ISSUE THREAD

**Issue by lakario** [aws/aws-toolkit-vscode#2603]
The specification for "Amazon States Language (YAML)" does not support comments. Any attempt to comment (or uncomment) YAML in an "Amazon States Language (YAML)" file has no effect in the editor (the command is a no-op) and using the "Format Document" command will strip any comments which have been added. 

## Feature Request

AWS Toolkit and the "Amazon States Language (YAML)" language specification should allow for standard `# YAML comment syntax` within the body of a state machine. Further, the "Format Document" command should not remove comments from a document which contains them.

```
  StartAt: Pass
  States:
    Pass:
      # Hello, I'm a comment
      Type: Pass
      Result: Hello, world
      End: true
```

![Format Document](https://i.imgur.com/4f1Dk1V.gif)
