### ISSUE TITLE
ApiAuth parameter AddDefaultAuthorizerToCorsPreflight incorrectly reported as invalid

### ISSUE THREAD

**Issue by deltafactory** [aws/aws-toolkit-vscode#2627]
**Describe the bug**

When trying to create a AWS::Serverless::API resource the Auth parameter AddDefaultAuthorizerToCorsPreflight does not validate.
This property is documented [here](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-api-apiauth.html#sam-api-apiauth-adddefaultauthorizertocorspreflight).

**To Reproduce**

1. Add AddDefaultAuthorizerToCorsPreflight to template.yaml in Visual Studio Code.

Example:
```
  ApiEndpoint:
    Type: AWS::Serverless::API
    Properties:
      ...
      Auth:
        AddDefaultAuthorizerToCorsPreflight: False
      ...
```

**Expected behavior**

This should validate.

**Desktop (please complete the following information):**

OS:  Windows_NT x64 10.0.19044
Visual Studio Code Extension Host Version:  1.67.0
AWS Toolkit Version:  1.37.0

**Additional context**

Similar situation as reported in #2467
