### ISSUE TITLE
sam.schema.json: More valid CloudFormation constructs not recognized

### ISSUE THREAD

**Issue by svenemtell** [aws/aws-toolkit-vscode#2837]
#### Describe the bug

This bug report lists a number of problems, just like #1978.
As mentioned, the YAML schema validation of AWS Toolkit is not very usable when you get complaints like these. Instead of helping me, the validation makes me insecure.

See details of issues below.

_Property ApiId is not allowed_

```
  MyHttpApi:
    Type: AWS::Serverless::HttpApi

  MyFunction:
    Type: AWS::Serverless::Function
    ...
      Events:
        MyApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyHttpApi # <-- error: Property ApiId is not allowed.
            Method: POST
            Path: /test
```

_Incorrect type. Expected "string"_
My understanding is that you usually don't need to quote strings in YAML (https://stackoverflow.com/questions/19109912/yaml-do-i-need-quotes-for-strings-in-yaml). Or am I misunderstanding something?

```
  MyOtherFunction:
    Type: AWS::Serverless::Function
    ...
      ProvisionedConcurrencyConfig:
        ProvisionedConcurrentExecutions: 1 # <-- error: Incorrect type. Expected "string".

  MyTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties: 
      ContainerDefinitions: 
        - Cpu: 0 # <-- error: Incorrect type. Expected "string".
    ...
      Memory: 8192 # <-- error: Incorrect type. Expected "string".

  MyQueue:
    Type: AWS::SQS::Queue
    Properties: 
    ...
      QueueName: MyQueue.fifo

  MyStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
    ...
      DefinitionSubstitutions:
        TestFunction: !Sub
          - ${Arn}:prod # <-- error: Incorrect type. Expected "string".
          - { Arn: !GetAtt MyOtherFunction.Arn } # <-- error: Incorrect type. Expected "string".
    ...
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Sub
              - ${Name}:prod # <-- error: Incorrect type. Expected "string".
              - { Name: !Ref MyOtherFunction } # <-- error: Incorrect type. Expected "string".
    ...
        - SQSSendMessagePolicy:
            QueueName: MyQueue.fifo # <-- error: Incorrect type. Expected "string".
```

#### To reproduce

Create a CloudFormation template with any of the above constructs.

#### Expected behavior

All valid CloudFormation syntax would be correctly recognized. The examples above should not produce any of the marked errors.

#### Desktop (please complete the following information):

OS: macOS 12.5 (Monterey) on Apple Silicon
Visual Studio Code Version: v1.70.2
AWS Toolkit Version: v1.48.0
