### ISSUE TITLE
AWS::Serverless::Connector linter error

### ISSUE THREAD

**Issue by mustafa-colakoglu** [aws/aws-toolkit-vscode#2998]
## Problem
When i want to use Serverless Connector, I m getting linter error.

value is not accepted. valid values: "aws::acmpca::certificate"

## Steps to reproduce the issue

Write resource to template.yaml file

![image](https://user-images.githubusercontent.com/9257902/203056883-f1890fff-647d-45ae-914e-2c598286811a.png)
![image](https://user-images.githubusercontent.com/9257902/203056959-f5e5c0df-ae95-45af-bb1c-903dabc1a8fd.png)

-   OS: Windows 10
-   Visual Studio Code version: latest
-   AWS Toolkit version: latest

We don't use this extension before fix this.

**Comment by justinmk3** [comment]
Are you still seeing this issue?

AWS Toolkit 1.65+ includes an updated SAM/CFN json-schema from : 
https://raw.githubusercontent.com/aws/serverless-application-model/main/samtranslator/schema/schema.json

**Comment by avoidik** [comment]
I am also facing similar issue even with the `modeline` on top, this is somehow relevant to https://github.com/aws/aws-toolkit-vscode/issues/1978

```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/aws/serverless-application-model/main/samtranslator/schema/schema.json
```

```yaml
AbcDef:
  Type: AWS::Serverless::Function # <- recognized as AWS::ACMPCA::Certificate
  Environment:
    ...
  Properties:
    ...
```
