### ISSUE TITLE
AWS SAM: Property DisableExecuteApiEndpoint is not allowed on AWS::Serverless::Api resource type

### ISSUE THREAD

**Issue by dylan8902** [aws/aws-toolkit-vscode#3102]
## Problem

The SAM schema is missing the `DisableExecuteApiEndpoint` property on `AWS::Serverless::Api` resource type event though it is valid and part of the schema docs[1] and implementation [2]

[1] https://github.com/awsdocs/aws-sam-developer-guide/blob/main/doc_source/sam-resource-api.md#user-content-sam-api-disableexecuteapiendpoint
[2] https://github.com/aws/serverless-application-model/blob/v1.57.0/samtranslator/schema/aws_serverless_api.py#L180

## Steps to reproduce the issue

1. Create new SAM template
2. Add an AWS::Serverless::Api resource with DisableExecuteApiEndpoint, for example:
```yaml
  api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Cors: "'*'"
      Description: My cool API
      TracingEnabled: True
      OpenApiVersion: "3.0.2"
      DisableExecuteApiEndpoint: true
```
![image](https://user-images.githubusercontent.com/150938/212936418-410ea086-9c58-4f35-b943-1df6f8fe3cb7.png)

## Expected behavior

The YAML schema should show valid as it deploys correctly

## System details (run the `AWS: About Toolkit` command)

-   OS: Darwin arm64 22.2.0
-   Visual Studio Code version: 1.74.3
-   AWS Toolkit version: 1.61.0
