### ISSUE TITLE
Users can add a lambda function to the resource list in their Sam template to reduce errors in template configuration

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#316]
Once a user has iterated on their lambda function and is happy with it, they may want a convenient way to produce an initial sam template resource that references this function. This becomes more useful as the toolkit adds actions that operate on sam templates and sam template resources.

Prompting for resource name and runtime, it should be possible to auto-generate:

```yaml
    SOME_RESOURCE_NAME:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: APPROPRIATE_LOCATION/
            Handler: APPROPRIATE_HANDLER
            Runtime: APPROPRIATE_RUNTIME
```

Acceptance Criteria:
* user has a way to produce sam template resource definition for a function of interest
