### ISSUE TITLE
CFN Dynamic Reference to SSM param and Intrinsic Functions not working with templated InvokeTarget

### ISSUE THREAD

**Issue by abest-halcaeon** [aws/aws-toolkit-vscode#3174]
## Problem

For debugging lambda functions in VSCode through the AWS SAM template, I'm using a direct-invoke with an invoke target of type Template ( https://docs.aws.amazon.com/toolkit-for-vscode/latest/userguide/serverless-apps-run-debug-config-ref.html ) which includes a reference to a SAM template and the logical ID in that template.

The template transform does not process Dynamic References ( https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html ) and also does not allow those references in intrinsic functions, like Fn:Sub.

Let's say I have a SSM parameter:
 Key: /staging/cloudformation/lambda-layer/arn
 Value: some:arn:example

I also have a template parameter "Bar" which is set to "staging"

!Sub "FOO {{resolve:ssm:/${Bar}/cloudformation/lambda-layer/arn}}"

In CFN will resolve to "FOO some:arn:example"

In this toolkit it resolves to : "FOO {{resolve:ssm:/Bar/cloudformation/lambda-layer/arn}}"

Removing the Fn:Sub and just leaving it: "{{resolve:ssm:/staging/cloudformation/lambda-layer/arn}}"

Still only resolves to:  "{{resolve:ssm:/staging/cloudformation/lambda-layer/arn}}"

So, it's neither executing the intrinsic function inside the reference or resolving the SSM parameter

## Steps to reproduce the issue

1. Create an SSM parameter
2. Create a new templated SAM Function that prints an environment variable
3. Set the environment variable in the template to reference this SSM parameter, through a Fn:Sub intrinsic function
4. Create a launch config to call the above SAM Template
5.  Debug the launch config

## Expected behavior

I expect it to work as CFN does, to process the intrinsic function and then resolve the dynamic reference

## System details (run the `AWS: About Toolkit` command)

-   OS: Windows 10
-   Visual Studio Code version: 1.75.1
-   AWS Toolkit version: 1.62.0

**Comment by abest-halcaeon** [comment]
SSM Parameters do not work either. The "Type" is completely ignored and it's all treated like a string.

Create an SSM Parameter "my-test-layer" with the ARN From a valid lambda layer. Create a launch config for the following resource, and it will not run, because it says "my-test-layer" is not a valid arn. Instead replayce "my-test-layer" with the actual arn value, and suddenly it will work.

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: WizardApp

Parameters:
  TestLambdaLayer:
    Type: AWS::SSM::Parameter::Value<String>
    Default: 'my-test-layer'

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Layers:
        - !Ref TestLambdaLayer	  
      Architectures:
        - x86_64
   ```
