### ISSUE TITLE
sam start almost every time fails: VersionNotParseable ... sam.cmd

### ISSUE THREAD

**Issue by saweisulzer** [aws/aws-toolkit-vscode#3524]
## Problem

```
AWSTemplateFormatVersion: 2010-09-09
Description:
  GeneratorCdk

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
  'AWS::Serverless-2016-10-31'

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    Tracing: Active
  Api:
    TracingEnabled: True

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # This is an SQS queue with all default configuration properties. To learn more about the available options, see
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sqs-queues.html
  SimpleQueue:
    Type: AWS::SQS::Queue
  
  # This is the Lambda function definition associated with the source code: sqs-payload-logger.js. For all available properties, see
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  SQSPayloadLogger:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/Generator/
      Handler: generator::Generator.EtsGeneratorFunction::FunctionHandler
      Runtime: dotnet6
      Architectures:
        - x86_64
      MemorySize: 1024
      Timeout: 300
      Events:
        SQSQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt SimpleQueue.Arn
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole

Outputs:  
  AppBucketArn:
    Description: "SQS Queue ARN"
```

## Steps to reproduce the issue

1. have template.yaml as ^^^
2. click on AWS: Add Debug Configuration
3. start the generated config

## Expected behavior
SAM build app and starts it

but fails with:
2023-06-05 18:42:59 [ERROR]: log level: info
2023-06-05 18:42:59 [INFO]: endpoints: retrieving AWS endpoints data
2023-06-05 18:42:59 [INFO]: OS: Windows_NT x64 10.0.19045
2023-06-05 18:42:59 [INFO]: Visual Studio Code extension host:  1.78.2
2023-06-05 18:42:59 [INFO]: AWS Toolkit:  1.76.0
2023-06-05 18:42:59 [INFO]: node: 16.17.1
2023-06-05 18:42:59 [INFO]: electron: 22.5.2
2023-06-05 18:42:59 [INFO]: telemetry cache not found: 'c:\Users\%USER%\AppData\Roaming\Code\User\globalStorage\amazonwebservices.aws-toolkit-vscode\telemetryCache'
2023-06-05 18:45:22 [WARN]: samCliLocator: found invalid SAM CLI (VersionNotParseable): C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd
2023-06-05 18:45:24 [WARN]: samCliLocator: found invalid SAM CLI (VersionNotParseable): C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd
2023-06-05 18:45:24 [INFO]: SAM CLI location (version: undefined): undefined
2023-06-05 18:45:24 [ERROR]: SamLaunchRequestError: SAM CLI was not found [MissingSamCli]

## System details (run the `AWS: About Toolkit` command)

OS: Windows_NT x64 10.0.19045
Visual Studio Code extension host:  1.78.2
AWS Toolkit:  1.76.0
node: 16.17.1
electron: 22.5.2

sam is SAM CLI, version 1.85.0
