### ISSUE TITLE
debug CDK SAM typescript lambda of type "AWS::Lambda::Function"

### ISSUE THREAD

**Issue by azgorov** [aws/aws-toolkit-vscode#4281]
## System details (run the `AWS: About Toolkit` command)

-   OS: MacOs Sonoma 14.2.1
-   Visual Studio Code version: 1.85.1 
-   AWS Toolkit version: 2.5.0
-  SAM: 1.107.0

## Question

Is debug config works with AWS CDK synth generated template? 

Steps to reproduce:

1. Generate init app with cdk.
2. Add NodejsFunction
3. cdk synth --no-staging > template.yml      
4.  sam local invoke xxDE507B92 -e events/xx.json -this command works without any issues.

if I try normal node attachment to sam debugging works with specific localRoot

1.  sam local invoke xxDE507B92 -d 5858 -e events/xx.json
2. config:
   ```
   {
            "name": "Attach to SAM Local",
            "type": "node",
            "request": "attach",
            "address": "localhost",
            "port": 5858,
            "localRoot": "${workspaceRoot}/cdk.out/asset.494325ce081b1d56eca9757238468014df0442a53c07341f158a22fdd2199d83/",
            "remoteRoot": "/var/task",
            "protocol": "inspector"
        }
   ```

if I try "AWS: Add SAM Debug Configuration" with synth template I got something like :

```
{
            "type": "aws-sam",
            "request": "direct-invoke",
            "name": "xx:xxDE507B92 (nodejs18.x)",
            "invokeTarget": {
                "target": "template",
                "templatePath": "${workspaceFolder}/template.yml",
                "logicalId": "xxDE507B92"
            },
            "lambda": {
                "payload": {},
                "environmentVariables": {}
            }
        },
```

Which looks fine but trying to run it I've got an exception:

```
2024-01-15 15:43:03 [ERROR]: SamLaunchRequestError: Invalid launch configuration: Template Resource xxDE507B92 in Template file /folder_xx/template.yml needs to be of type AWS::Serverless::Function or AWS::Lambda::Function [BadLaunchConfig]
```

Template.yml contains following resource:

```
  xxDE507B92:
    Type: AWS::Lambda::Function
    Properties:
      Architectures:
        - arm64
      Code:
        S3Bucket:
          Fn::Sub: cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}
        S3Key: 494325ce081b1d56eca9757238468014df0442a53c07341f158a22fdd2199d83.zip
      Environment:
        Variables:
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
      Handler: index.handler
      Role:
        Fn::GetAtt:
          - xxServiceRoleEA518023
          - Arn
      Runtime: nodejs18.x
    DependsOn:
      - xxServiceRoleEA518023
    Metadata:
      aws:cdk:path: XxStack/xx/Resource
      aws:asset:path: /folder_xx/cdk.out/asset.494325ce081b1d56eca9757238468014df0442a53c07341f158a22fdd2199d83
      aws:asset:is-bundled: true
      aws:asset:property: Code
```
