### ISSUE TITLE
Amazon Q incorrectly validates AWS SAM template 

### ISSUE THREAD

**Issue by sliedig** [aws/aws-toolkit-vscode#5250]
## Problem
Q does not recognise that the Globals section exists in the template and incorrectly marks the function definitions as invalid. 

```
Globals:
  Function:
    Runtime: dotnet8
    Timeout: 30
    MemorySize: 512
    Architectures:
      - x86_64
    Tracing: Active
    ....

```

![image](https://github.com/aws/aws-toolkit-vscode/assets/597073/fd0b7601-80df-4d42-a0c7-bdbd4d71325e)

## Steps to reproduce the issue
Nothing is required to reproduce the error, Q automatically marks these resources as invalid.

## Expected behavior
Do not mark the function as invalid.

## System details (run `AWS: About` and/or `Amazon Q: About`)

OS: Darwin arm64 23.5.0
Visual Studio Code extension host:  1.90.2
Amazon Q:  1.11.0
node: 20.9.0
electron: 29.4.0
