### ISSUE TITLE
SAM Python Debugger fails to respect breakpoints in VSC when DockerContext is modified to ./

### ISSUE THREAD

**Issue by Winne004** [aws/aws-toolkit-vscode#5353]
## Problem
SAM Python Debugger fails to respect breakpoints in VSC when `DockerContext` is modified to `./` 

## Steps to reproduce the issue

1. Create new SAM application using the VSCode toolkit 
2. Modify `template.yaml` from: 
```
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./hello_world
      DockerTag: python3.12-v1
```
to 
```
    Metadata:
      Dockerfile: hello_world/Dockerfile
      DockerContext: ./
      DockerTag: python3.12-v1
```
4. Modify `Dockerfile` (`COPY ./hello_world/app.py requirements.txt ./`) to use the correct path. 
5. Set breakpoint in app.py
6. Debug function (using either of the default debug configurations). 
7. Function launches, debugger attaches, but breakpoints are not respected 

## Expected behaviour

Function launches, debugger attaches, and breakpoints are respected 

## System details (run `AWS: About` and/or `Amazon Q: About`)
```
OS: Darwin arm64 23.5.0
Visual Studio Code extension host:  1.91.1
AWS Toolkit:  3.15.0
node: 20.9.0
electron: 29.4.0
```
Should it make a difference, I am using Colima instead of Docker. 
```
colima version 0.6.9
```
