### ISSUE TITLE
CodeLens is missing if handler starts with a folder

### ISSUE THREAD

**Issue by abrooksv** [aws/aws-toolkit-vscode#661]
**Describe the bug**

**To Reproduce**
Given:
```
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello-world/
      Handler: foo/app.lambdaHandler
      Runtime: nodejs10.x
```

shows no CodeLens on the handler

**Expected behavior**
There should be a code lens
