### ISSUE TITLE
CodeLens not working when Environment Variables are set

### ISSUE THREAD

**Issue by chechedotmx** [aws/aws-toolkit-vscode#683]
**Describe the bug**
When using Environment Variables in template.yaml Code Lens stop working

**To Reproduce**

I have the next template.yaml that doesn´t show "Run Locally | Debug Locally | Configure" on function handler

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for SATExtractor

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  LoginSatFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./src/LoginSatFunction/
      Handler: LoginSatFunction::LoginSatFunction.Function::FunctionHandler
      Runtime: dotnetcore2.1
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          ANTI_CAPTCHA_KEY: xxx
          ATTEMPS_LOGIN: 3
      Events:
        LoginSat:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  LoginSatApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  LoginSatFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt LoginSatFunction.Arn
  LoginSatFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt LoginSatFunctionRole.Arn
```

(the same happens with the nodejs sample template.yaml)

I have already validated the template and it´s ok:

```
ChecheBook:serverless-apps cheche$ sudo sam validate -t template.yaml --profile apps
2019-07-11 12:47:33 Found credentials in shared credentials file: ~/.aws/credentials
/Users/cheche/git/serverless-apps/template.yaml is a valid SAM Template
```

But when I see the AWS toolkit logs it shows something like this and does not show the options in CodeLens:

```
2019-07-11 12:52:52 [ERROR]: Could not generate 'configure' code lens for handler 'LoginSatFunction::LoginSatFunction.Function::FunctionHandler' Error: Unable to find a sam template associated with handler 'LoginSatFunction::LoginSatFunction.Function::FunctionHandler' in /Users/cheche/git/serverless-apps/src/LoginSatFunction/Function.cs.
	at /Users/cheche/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.0.0/out/src/shared/codelens/codeLensUtils.js:127:15
	at Generator.next (<anonymous>)
	at fulfilled (/Users/cheche/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.0.0/out/src/shared/codelens/codeLensUtils.js:8:58)
```

It started working again when I remove those variables:

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for SATExtractor

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  LoginSatFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./src/LoginSatFunction/
      Handler: LoginSatFunction::LoginSatFunction.Function::FunctionHandler
      Runtime: dotnetcore2.1
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          #ANTI_CAPTCHA_KEY: xxxx
          #ATTEMPS_LOGIN: 3
      Events:
        LoginSat:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  LoginSatApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  LoginSatFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt LoginSatFunction.Arn
  LoginSatFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt LoginSatFunctionRole.Arn

```

**Expected behavior**
Show CodeLens options with Environment Variables

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.5
 - Visual Studio Code Version: 1.36.1
 - AWS Toolkit for Visual Studio Code Version: 1.36.1

**Comment by awschristou** [comment]
Hi @chechedotmx thank you for reporting this. It looks like the toolkit is currently having issues with the `ATTEMPS_LOGIN: 3` environment variable. I will investigate further, but as a workaround, can you please try  changing that to `ATTEMPS_LOGIN: '3'` and see if the CodeLenses appear?

**Comment by chechedotmx** [comment]
Thanks, @awschristou that worked as a workaround, not sure what happens if I deploy this template with that configuration but at least code lens is working

The next code worked:
```
        Variables:
          ANTI_CAPTCHA_KEY: ''
          ATTEMPS_LOGIN: ''
```

The next code didn´t work
```
        Variables:
          ANTI_CAPTCHA_KEY:
          ATTEMPS_LOGIN:
```
The next code worked:
```
        Variables:
          ANTI_CAPTCHA_KEY: 'xxx'
          ATTEMPS_LOGIN: '3'
```
The next code didn´t work
```
        Variables:
          ANTI_CAPTCHA_KEY: xxxx
          ATTEMPS_LOGIN: 3
```

**Comment by awschristou** [comment]
We will update the toolkit so that it does not consider numeric values to be an error.
I still have to investigate if an empty value is allowed, and can follow up on that.

**Comment by uncledru** [comment]
Just a note - may be the same issue as above but it doesn't work when you use a ref either:

```yaml
Environment:
  Variables:
    EVENTER_URL: "/subscribers"
    LOG_LEVEL: !Ref LogLevel
```
