### ISSUE TITLE
Javascript codelenses do not handle nested code files

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#757]
Unsure if this affects other runtimes.

The Toolkit does not show CodeLenses for a SAM App with the following layout:

Files:
```
/template.yml    (SAM Template)
/package.json (manifest)
/src
    /handlers
        /code.js     (contains handler function called myFunction)
```

SAM Template Resource:
```
  SomeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/handlers/code.myFunction
      ... (other properties)
```
