### ISSUE TITLE
How to set "environmentVariables": {} in templates.json

### ISSUE THREAD

**Issue by pcharasala** [aws/aws-toolkit-vscode#795]
Have been looking for help hours on how to set "environmentVariables": {} in .aws templates.json.
Have tried "environmentVariables": {"key":"value"}
"environmentVariables": {"Variablkes":[{"key":"value"}]}
"environmentVariables": [{"key":"value"},]

None works.
Please help.

**Comment by awschristou** [comment]
Hi @pcharasala the proper configuration is "environmentVariables": {"key":"value"} , however the environment variable must also be defined in your SAM Template file.

Here is an example...

My SAM Template (template.yaml) file has the following resource that contains an environment variable called **SAMPLE1**:

```yaml
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandlerN10
      Runtime: nodejs10.x
      Environment:
        Variables:
          SAMPLE1: Default Sample 1 Value
```

My configuration for environment variables looks like this:
```json
          "environmentVariables": {
              "SAMPLE1": "My sample 1 value"
          }
```

Can you please check your template and configuration and report back?

**Comment by pcharasala** [comment]
> Hi @pcharasala the proper configuration is "environmentVariables": {"key":"value"} , however the environment variable must also be defined in your SAM Template file.
> 
> Here is an example...
> 
> My SAM Template (template.yaml) file has the following resource that contains an environment variable called **SAMPLE1**:
> 
> ```yaml
> Resources:
>   HelloWorldFunction:
>     Type: AWS::Serverless::Function
>     Properties:
>       CodeUri: hello-world/
>       Handler: app.lambdaHandlerN10
>       Runtime: nodejs10.x
>       Environment:
>         Variables:
>           SAMPLE1: Default Sample 1 Value
> ```
> 
> My configuration for environment variables looks like this:
> 
> ```json
>           "environmentVariables": {
>               "SAMPLE1": "My sample 1 value"
>           }
> ```
> 
> Can you please check your template and configuration and report back?

Thank you! That works.
The piece I was missing is the fact that environment variable keys must be there at both template.yaml and templates.json.
I have tested with multiple variables too and I am giving it here could be useful to someone else.
In the temlate.yaml..
```
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandlerN10
      Runtime: nodejs10.x
      Environment:
        Variables:
          SAMPLE1: Default Sample 1 Value
         SAMPLE2: Default Sample2 Value
```
and in templates.json running configuration as
```
{
    "templates": {
        "sam-app/template.yaml": {
            "handlers": {
                "app.lambda_handler": {
                    "event": {},
                    "environmentVariables": {"SAMPLE1": "My sample 1 value", "SAMPLE2": "My Sample2"}
                }
            }
        }
    }
}
```
