### ISSUE TITLE
CodeLens does not appear if two handlers have the same name

### ISSUE THREAD

**Issue by jamiethorpe** [aws/aws-toolkit-vscode#912]
**Describe the bug**
I noticed code lenses stopped appearing after adding a second function to my project and template.yaml file. I then found that they reappeared after changing the handler filenames to be different and modifying the reference in template.yaml.

**To Reproduce**

1. Create a new SAM project `sam init`
2. Duplicate the example hello-world function and name it something else (I'm using get-order), but leave the handler as app.js. You can create an entirely new function if you prefer.
3. Add a new function record in template.yaml:
```
  GetOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get-order/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        GetOrder:
          Type: Api
          Properties:
            Path: /order
            Method: get
```
4. Code lenses will now not appear for either function
5. Modifying the app.js filenames to something else (I used hello-world.js and get-order.js) and changing the Handler property in template.yaml to match (hello-world.lambdaHandler and get-order.lambdaHandler) will fix it.
6. I also tried moving the Handler to the Global property and the code lenses did not appear:
```
Globals:
  Function:
    Handler: app.lambdaHandler
    Timeout: 3
```

**Expected behavior**

I assumed that having the same handler name would be okay in different functions. I also tried adding the folder name to the handler property and didn't have any luck. The template file still validates when running `sam validate` so I don't believe it's an issue with the template.

**Desktop (please complete the following information):**

-   OS: Ubuntu 18.04
-   Visual Studio Code Version: 1.41.1
-   AWS Toolkit for Visual Studio Code Version: 1.5.0
